ProyectoChico/ViewModels/ContactView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoChico.ViewModels
{
    public class ContactView
    {
        [Required]
        [MinLength(5,ErrorMessage ="Minimo 5 caracteres en nombre")]
        public string nombre { get; set; }
        [Required]
        [EmailAddress(ErrorMessage ="Email invalido")]
        public string email { get; set; }
        [Required]
        [MaxLength(50,ErrorMessage ="Maximo 50 caracteres en contenido")]
        public string contenido { get; set; }
    }
}

ProyectoChico/Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoChico.Data;
using ProyectoChico.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoChico.Controllers
{
    public class AppController : Controller
    {
        private readonly JotaContext context;
        private readonly IJotaRepository repository;

        public AppController(IJotaRepository repository)
        {
         
            this.repository = repository;
        }
       
        public IActionResult Index()
        {
            
            return View();
        }

        //[HttpGet("Contacto")]
        public IActionResult Contact()
        {
           
           
            return View();
        }
        [HttpPost]
        public IActionResult Contact(ContactView model)
        {

            if (ModelState.IsValid)
            {

            }
            else
            {

            }
            ViewBag.UserMessage = "Mail enviado";
            return View();
        }

        [HttpGet("Acerca")]
        public IActionResult About()
        {
          

            return View();
        }
        
        [HttpGet("Tienda")]
        public IActionResult Shop()
        {
            var results = repository.obtenerTodo();
            return View(results);

        }
    }
}

ProyectoChico/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProyectoChico.Pages
{
    public class ErrorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ProyectoChico/Views/App/About.cshtml
<h2>@ViewBag.Tittle</h2>

ProyectoChico/Views/App/Contact.cshtml
@{
    ViewBag.Tittle = "Contacto";
}
@model ContactView

@section scripts{ 
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-6 col-md-offset-3">
    <div class="well">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="nombre">Your name</label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="email">Email</label>
                <input asp-for="email" type="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="contenido">Contenido</label>
                <textarea asp-for="contenido" rows="4" class="form-control"></textarea>
                <span asp-validation-for="contenido" class="text-danger"></span>
            </div>

          
            <div class="form-group">
            <input type="submit" value="Enviar" class="btn btn-primary" />
                <div class="text-success"> @ViewBag.UserMessage </div>
            </div>
        </form>
    </div>
</div>

ProyectoChico/Views/App/Index.cshtml
    ViewBag.Tittle = "Home page";
  
}



    <div class="compra">
        <h3>Comprar</h3>
        <ul class="productos">
            <li>Twenty One Pilots</li>
            <li>Precio:20$</li>
            <li>Tittle:</li>
            <li>Descripcion:Deluxe</li>
        </ul>
        <button id="boton">Comprar</button>
    </div>

    

    <div>
        <div id="tituloLogin">Login</div>
        <form class="popup">
            <div>
                <label>Usuario</label>
                <input type="text" />
            </div>
            <div>
                <label>Password</label>
                <input type="password" />
            </div>
            <div>
                <label>Recordarme</label>
                <input type="checkbox" />
            </div>

            <div>

                <input type="submit" />
            </div>
        </form>
    </div>

ProyectoChico/Views/App/Shop.cshtml
@model IEnumerable<Product>
<h1>Tienda</h1>
<p>Conteo: @Model.Count() </p>

@foreach (var p in Model)
{
    <div class="col-md-3">
        <div class="well well-sm">
            <img  src="~/img/@(p.ArtId).jpg"  alt="@p.Title " class="img-responsive"/>
            <h3> @p.Category - @p.Size</h3>
            <ul class="productos">
                <li>@p.Title</li>
                <li>Precio:@p.Price</li>
             
                <li>Descripcion:@p.ArtDescription</li>
            </ul>
            <button id="boton">Comprar</button>
        </div>
    </div>
}

ProyectoChico/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet


<!DOCTYPE html>
<html>
<head>
    <script src="~/js/index.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <meta charset="utf-8" />    
    
    <title>@ViewBag.Tittle</title>

   
   
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <div class="navbar navbar-default">
        <header class="container">


            <div class="navbar-header">
                <div class="navbar-brand"> <i class="fa fa-apple ">  Jota</i></div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
            </div>
            <div id="menu" class="collapse navbar-collapse" >
                <ul class="nav navbar-nav">
                    <li><a asp-controller="App" asp-action="Index">Home</a></li>
                    <li><a asp-controller="App" asp-action="Contact">Contacto</a></li>
                    <li><a asp-controller="App" asp-action="About">Acerca</a></li>
                    <li><a asp-controller="App" asp-action="Shop">Tienda</a></li>
                </ul>
            </div>
           


        </header>
    </div>
    <h2 class="text-center">@ViewBag.Tittle</h2>
    <section class="container">
        @RenderBody()
    </section>
    <footer class="container text-center">Copyright 2017 Jota</footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts",false)


</body>
</html>